version: "3"
containers:
- name: workstation
  image: codercom/code-server
  cmd: code-server workspace /app --user-data-dir /user-data --auth none --disable-telemetry
  ports:
  - 8080
  - 3000
  memory: 2048
- name: mysql
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysql
  ports:
  - 3306