version: "3"
containers:
- name: workstation
  image: codercom/code-server
  memory: 2048
  cpu: 4
  cmd: code-server workspace /app --user-data-dir /user-data --auth none --disable-telemetry
  ports:
  - 8080
  - 3000
